/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author usiel
 */
import javax.swing.JOptionPane;
import org.json.JSONObject;
import system_inventary.clasification;

public class editClasification extends javax.swing.JFrame {

    /**
     * Creates new form editClasification
     */
    private Integer id;
    
    clasification objClasification = new clasification();
    
    public editClasification(Integer id) {
        this.id = id;
        initComponents();
        clasification_data(id);
        
        this.setLocationRelativeTo(null);
    }

    public void clasification_data(Integer id) {
        clasification clasificationData = new clasification();
        JSONObject data = new JSONObject();
        data = clasificationData.show_clasification(id);
        Integer idClasification = data.getInt("id");
        String nameClasification = data.getString("clasification");

        txtEditClasification.setText(nameClasification);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEditClasification = new javax.swing.JLabel();
        txtEditClasification = new javax.swing.JTextField();
        lblClasificationEditClasification = new javax.swing.JLabel();
        btnEditClasification = new javax.swing.JButton();
        btnCancelEditClasification = new javax.swing.JButton();

        setTitle("Editar clasificacion");

        lblEditClasification.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblEditClasification.setText("Editar clasificacion");

        lblClasificationEditClasification.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblClasificationEditClasification.setText("Clasificacion:");

        btnEditClasification.setText("Editar");
        btnEditClasification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditClasificationActionPerformed(evt);
            }
        });

        btnCancelEditClasification.setText("Cancelar");
        btnCancelEditClasification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelEditClasificationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditClasification)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelEditClasification)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClasificationEditClasification)
                .addGap(10, 10, 10)
                .addComponent(txtEditClasification, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(lblEditClasification)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(lblEditClasification)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditClasification, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClasificationEditClasification))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditClasification, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelEditClasification, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelEditClasificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelEditClasificationActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelEditClasificationActionPerformed

    private void btnEditClasificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditClasificationActionPerformed
        String clasificationEdit = txtEditClasification.getText();
        boolean result = objClasification.update_clasification(this.id, clasificationEdit);
        if (result == true) {
            JOptionPane.showMessageDialog(null, "Clasificacion editada con exito");
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Algo a ocurrido mientras se intentaba editar dicha clasificacion");
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnEditClasificationActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelEditClasification;
    private javax.swing.JButton btnEditClasification;
    private javax.swing.JLabel lblClasificationEditClasification;
    private javax.swing.JLabel lblEditClasification;
    private javax.swing.JTextField txtEditClasification;
    // End of variables declaration//GEN-END:variables
}
