/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.Array;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import system_inventary.medicine;
import org.json.JSONObject;
import system_inventary.clasification;

/**
 *
 * @author usiel
 */
public class editMedicine extends javax.swing.JFrame {

    /**
     * Creates new form edit_medicine
     */
    private Integer id;
    medicine objMedicine = new medicine();
    clasification objClasification = new clasification();

    public editMedicine(Integer id) {
        this.id = id;
        initComponents();
        medicine_data(id);
        this.setLocationRelativeTo(null);
    }

    public void medicine_data(Integer id) {
        JSONObject data = new JSONObject();
        data = objMedicine.show_medicine(id);
        JSONArray clasifications = new JSONArray();
        clasifications = objClasification.show_clasifications();

        Integer idMedicine = data.getInt("id");
        String nameMedicine = data.getString("name");
        String descriptionMedicine = data.getString("description");
        String quantityMedicine = data.getString("quantity");
        Integer idClasification = data.getInt("idClasification");
        String clasification = data.getString("clasification");

        txtKeyEditMedicine.setText(String.valueOf(idMedicine));
        txtNameEditMedicine.setText(nameMedicine);
        txtDescriptionEditMedicine.setText(descriptionMedicine);
        txtQuantityEditMedicine.setText(String.valueOf(quantityMedicine));
        cmbClasificationEditMedicine.addItem(idClasification + ": " + clasification);
        for (int i = 0; i < clasifications.length(); i++) {
            Integer clasificationId = clasifications.getJSONObject(i).getInt("id");
            String clasificationClas = clasifications.getJSONObject(i).getString("clasification");
            if (idClasification != clasificationId) {
                cmbClasificationEditMedicine.addItem(clasificationId + ": " + clasificationClas);
            } 
        }
        //
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEditMedicine = new javax.swing.JLabel();
        lblKeyEditMEdicine = new javax.swing.JLabel();
        lblNameEditMedicine = new javax.swing.JLabel();
        lblDescriptionEditMedicine = new javax.swing.JLabel();
        lblClasificationEditMedicine = new javax.swing.JLabel();
        lblQuantityEditMedicine = new javax.swing.JLabel();
        txtKeyEditMedicine = new javax.swing.JTextField();
        txtNameEditMedicine = new javax.swing.JTextField();
        txtDescriptionEditMedicine = new javax.swing.JTextField();
        cmbClasificationEditMedicine = new javax.swing.JComboBox<>();
        txtQuantityEditMedicine = new javax.swing.JTextField();
        btnEditEditMedicine = new javax.swing.JButton();
        btnCancelEditMedicine = new javax.swing.JButton();

        lblEditMedicine.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblEditMedicine.setText("Editar medicamento");

        lblKeyEditMEdicine.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblKeyEditMEdicine.setText("Clave:");

        lblNameEditMedicine.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNameEditMedicine.setText("Nombre:");

        lblDescriptionEditMedicine.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDescriptionEditMedicine.setText("Descripcion:");

        lblClasificationEditMedicine.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblClasificationEditMedicine.setText("Clasificacion:");

        lblQuantityEditMedicine.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblQuantityEditMedicine.setText("Cantidad:");

        txtKeyEditMedicine.setEditable(false);
        txtKeyEditMedicine.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtKeyEditMedicine.setEnabled(false);

        txtQuantityEditMedicine.setEditable(false);
        txtQuantityEditMedicine.setToolTipText("");
        txtQuantityEditMedicine.setEnabled(false);

        btnEditEditMedicine.setText("Editar");
        btnEditEditMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditEditMedicineActionPerformed(evt);
            }
        });

        btnCancelEditMedicine.setText("Cancelar");
        btnCancelEditMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelEditMedicineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKeyEditMEdicine)
                    .addComponent(lblNameEditMedicine)
                    .addComponent(lblDescriptionEditMedicine)
                    .addComponent(lblClasificationEditMedicine)
                    .addComponent(lblQuantityEditMedicine))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbClasificationEditMedicine, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtQuantityEditMedicine, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKeyEditMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameEditMedicine)
                    .addComponent(txtDescriptionEditMedicine))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEditMedicine)
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btnEditEditMedicine)
                .addGap(18, 18, 18)
                .addComponent(btnCancelEditMedicine)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblEditMedicine)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKeyEditMEdicine)
                    .addComponent(txtKeyEditMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameEditMedicine)
                    .addComponent(txtNameEditMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescriptionEditMedicine)
                    .addComponent(txtDescriptionEditMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClasificationEditMedicine)
                    .addComponent(cmbClasificationEditMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantityEditMedicine)
                    .addComponent(txtQuantityEditMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditEditMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelEditMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelEditMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelEditMedicineActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelEditMedicineActionPerformed

    private void btnEditEditMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditEditMedicineActionPerformed
        Integer newId = Integer.parseInt(txtKeyEditMedicine.getText());
        String name = txtNameEditMedicine.getText();
        String description = txtDescriptionEditMedicine.getText();
        Integer clasification = Integer.parseInt(cmbClasificationEditMedicine.getSelectedItem().toString().replaceAll("\\D+",""));
        //Integer quantity = Integer.parseInt(txtQuantityEditMedicine.getText());
        boolean status = objMedicine.update_medicine(this.id, name, description, clasification);
        if (status == true) {
            JOptionPane.showMessageDialog(null, "Medicamento editado correctamente");
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Algo salio mal mientras se intentaba editar el medicamento");
        }
    }//GEN-LAST:event_btnEditEditMedicineActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelEditMedicine;
    private javax.swing.JButton btnEditEditMedicine;
    private javax.swing.JComboBox<String> cmbClasificationEditMedicine;
    private javax.swing.JLabel lblClasificationEditMedicine;
    private javax.swing.JLabel lblDescriptionEditMedicine;
    private javax.swing.JLabel lblEditMedicine;
    private javax.swing.JLabel lblKeyEditMEdicine;
    private javax.swing.JLabel lblNameEditMedicine;
    private javax.swing.JLabel lblQuantityEditMedicine;
    private javax.swing.JTextField txtDescriptionEditMedicine;
    private javax.swing.JTextField txtKeyEditMedicine;
    private javax.swing.JTextField txtNameEditMedicine;
    private javax.swing.JTextField txtQuantityEditMedicine;
    // End of variables declaration//GEN-END:variables
}
