/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author usiel
 */
import java.awt.Point;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.*;
import system_inventary.medicine;

public class medicines_main extends javax.swing.JFrame {

    /**
     * Creates new form medicines_main
     */

    public void tableMedicine() {
        medicine medicines = new medicine();
        JSONArray medicinesList = medicines.show_medicines();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Clave");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Clasificacion");
        modelo.addColumn("Cantidad");
        for (int i = 0; i < medicinesList.length(); i++) {
            Integer id = medicinesList.getJSONObject(i).getInt("id");
            String name = medicinesList.getJSONObject(i).getString("name");
            String description = medicinesList.getJSONObject(i).getString("description");
            String clasification = medicinesList.getJSONObject(i).getString("clasification");
            Integer quantity = medicinesList.getJSONObject(i).getInt("quantity");
            modelo.addRow(new Object[]{id, name, description, clasification, quantity});
        }
        tableMedicines.setModel(modelo);
    }

    public medicines_main() {
        initComponents();
        tableMedicine();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableMedicines = new javax.swing.JTable();
        btnDeleteMedicine = new javax.swing.JButton();
        btnEditMedicine = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuRegisterMedicine = new javax.swing.JMenu();
        jMenuHistorial = new javax.swing.JMenu();
        jMenuHistoryPersonalize = new javax.swing.JMenu();
        jMenuHistory = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Medicamentos");
        setSize(new java.awt.Dimension(1200, 400));

        tableMedicines.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tableMedicines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Nombre", "Descripcion", "Clasificacion", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(tableMedicines);

        btnDeleteMedicine.setText("Eliminar");
        btnDeleteMedicine.setPreferredSize(null);
        btnDeleteMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMedicineActionPerformed(evt);
            }
        });

        btnEditMedicine.setText("Editar");
        btnEditMedicine.setPreferredSize(null);
        btnEditMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditMedicineActionPerformed(evt);
            }
        });

        menuRegisterMedicine.setText("Registrar medicamento");
        menuRegisterMedicine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRegisterMedicineMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuRegisterMedicine);

        jMenuHistorial.setText("Historial");

        jMenuHistoryPersonalize.setText("Historial personalizado");
        jMenuHistoryPersonalize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHistoryPersonalizeMouseClicked(evt);
            }
        });
        jMenuHistorial.add(jMenuHistoryPersonalize);

        jMenuHistory.setText("Historial general");
        jMenuHistorial.add(jMenuHistory);

        jMenuBar1.add(jMenuHistorial);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDeleteMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnEditMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuRegisterMedicineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRegisterMedicineMouseClicked
        new registerMedicine().setVisible(true);
    }//GEN-LAST:event_menuRegisterMedicineMouseClicked

    private void btnDeleteMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMedicineActionPerformed
        try {
            Object idSelected = tableMedicines.getValueAt(tableMedicines.getSelectedRow(), 0);
            int confirm = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea eliminar el medicamento?");
            if (confirm == JOptionPane.OK_OPTION) {
                medicine medicine = new medicine();
                boolean result = medicine.delete_medicine(Integer.parseInt(idSelected.toString()));
                if (result == true) {
                        JOptionPane.showMessageDialog(null, "El medicamento a sido eliminado correctamente");
                }else{
                        JOptionPane.showMessageDialog(null, "Algo a salido mal mientras se intentaba eliminar el medicamento");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe de seleccionar un medicamento para poder eliminarlo");
        }
    }//GEN-LAST:event_btnDeleteMedicineActionPerformed

    private void btnEditMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditMedicineActionPerformed
        try{
            Object idSelected = tableMedicines.getValueAt(tableMedicines.getSelectedRow(), 0);
            Integer id = Integer.parseInt(idSelected.toString());
            new editMedicine(id).setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Debe de seleccionar un medicamento para poder editarlo");
        }
    }//GEN-LAST:event_btnEditMedicineActionPerformed

    private void jMenuHistoryPersonalizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHistoryPersonalizeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuHistoryPersonalizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(medicines_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(medicines_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(medicines_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(medicines_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new medicines_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteMedicine;
    private javax.swing.JButton btnEditMedicine;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHistorial;
    private javax.swing.JMenu jMenuHistory;
    private javax.swing.JMenu jMenuHistoryPersonalize;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuRegisterMedicine;
    private javax.swing.JTable tableMedicines;
    // End of variables declaration//GEN-END:variables
}
