/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package views;

/**
 *
 * @author usiel
 */
import javax.swing.JOptionPane;
import system_inventary.clasification;

public class registerClasification extends javax.swing.JFrame {

    /** Creates new form registerClasification */
    public registerClasification() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleRegisterClasification = new javax.swing.JLabel();
        txtClasificationRegisterClasification = new javax.swing.JTextField();
        lblClasificationRegisterClasification = new javax.swing.JLabel();
        btnRegisterClasification = new javax.swing.JButton();
        btnCancelRegisterClasification = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitleRegisterClasification.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitleRegisterClasification.setText("Registrar clasificacion");

        lblClasificationRegisterClasification.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblClasificationRegisterClasification.setText("Clasificacion:");
        lblClasificationRegisterClasification.setToolTipText("");

        btnRegisterClasification.setText("Registrar");
        btnRegisterClasification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterClasificationActionPerformed(evt);
            }
        });

        btnCancelRegisterClasification.setText("Cancelar");
        btnCancelRegisterClasification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelRegisterClasificationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegisterClasification)
                        .addGap(26, 26, 26)
                        .addComponent(btnCancelRegisterClasification))
                    .addComponent(txtClasificationRegisterClasification, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClasificationRegisterClasification)
                    .addComponent(lblTitleRegisterClasification))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitleRegisterClasification)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(lblClasificationRegisterClasification)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClasificationRegisterClasification, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisterClasification, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelRegisterClasification, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelRegisterClasificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelRegisterClasificationActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelRegisterClasificationActionPerformed

    private void btnRegisterClasificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterClasificationActionPerformed
        String newClasification = txtClasificationRegisterClasification.getText();
        clasification registerClasification = new clasification();
        boolean resp = registerClasification.register_clasification(newClasification);
        if (resp == true) {
            JOptionPane.showMessageDialog(null, "Se a agregado una nueva clasificacion satisfactoriamente");
        }else{
            JOptionPane.showMessageDialog(null, "Algo a salido mal mientras se intentaba agregar una nueva clasificacion");
        }
        this.setVisible(false);
    }//GEN-LAST:event_btnRegisterClasificationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerClasification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerClasification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerClasification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerClasification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerClasification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelRegisterClasification;
    private javax.swing.JButton btnRegisterClasification;
    private javax.swing.JLabel lblClasificationRegisterClasification;
    private javax.swing.JLabel lblTitleRegisterClasification;
    private javax.swing.JTextField txtClasificationRegisterClasification;
    // End of variables declaration//GEN-END:variables

}
